#spring.application.name=vat-nic-backend-demo
#spring.datasource.url=jdbc:postgresql://localhost:5432/vat_auth_db
#spring.datasource.username=vat_user
#spring.datasource.password=anirban@780

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=vat-nic-backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.datasource.url=jdbc:postgresql://localhost:5432/vat_portal
# spring.datasource.username=ganesh
# spring.datasource.password=ganesh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
