#spring.application.name=vat-nic-backend-demo
#spring.datasource.url=jdbc:postgresql://localhost:5432/vat_auth_db
#spring.datasource.username=vat_user
#spring.datasource.password=anirban@780

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=vat-nic-backend
server.address=0.0.0.0
server.port=${PORT:10000}

# spring.datasource.url=jdbc:postgresql://localhost:5432/K4

# spring.datasource.url=jdbc:postgresql://kamaleshuser:4abFnSvhn3Jv57noB4jlcISHRJns8pl7@dpg-d1efp3fgi27c73eid290-a.oregon-postgres.render.com/kamaleshdb
# spring.datasource.username=kamaleshuser
# spring.datasource.password=4abFnSvhn3Jv57noB4jlcISHRJns8pl7



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET_KEY}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
